[package]
name = "uxmlwriter"
version = "0.1.0"
edition = "2021"
authors = ["Madeleine Maria Ilyinichna"]
license = "BSD-3-Clause"
description = "A tiny drop-in replacement for xmlwriter"
keywords = ["xml"]

[dependencies]
